import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { Masthead } from "../components/masthead";
import { AboutUs } from "../components/aboutus";
import { Skills } from "../components/skills";
import { Works } from "../components/works";
import { TrustedBy } from "../components/trustedby";
import { ContactUs } from "../components/contactus";
import { Footer } from "../components/footer";
import useSWR from "swr";

const inter = Inter({ subsets: ["latin"] });

const fetcher = (input: any, init?: any) =>
  fetch(input, init).then((res) => res.json());

export default function Home() {
  const { data } = useSWR("/api/stats", fetcher);
  return (
    <>
      <Head>
        <title>Mikolajhere App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Masthead />
      <AboutUs />
      <Skills commits={data?.commits} />
      <Works />
      <TrustedBy />
      <ContactUs />
      <Footer />
    </>
  );
}
